<?php

/**
 * ##COPYRIGHT PLACEHOLDER##
 */

/**

 * BaseSetting
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $name
 * @property string $value
 * @property string $weight
 * @property string $id
 *
 * @method string  getName($load = true) Returns the current record's "name" value
 * @method string  getValue($load = true) Returns the current record's "value" value
 * @method string  getWeight($load = true) Returns the current record's "weight" value
 * @method string  getId($load = true) Returns the current record's "id" value
 * @method Setting setName($value, $load = true) Sets the current record's "name" value
 * @method Setting setValue($value, $load = true) Sets the current record's "value" value
 * @method Setting setWeight($value, $load = true) Sets the current record's "weight" value
 * @method Setting setId($value, $load = true) Sets the current record's "id" value
 *
 */
abstract class BaseSetting extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('name', 'string', 255, [
            'type' => 'string',
            'length' => 255,
            'notnull' => true,
        ]);
        $this->hasColumn('value', 'string', null, [
            'type' => 'string',
        ]);
        $this->hasColumn('weight', 'float', 4, [
            'type' => 'float',
            'length' => 4,
            'scale' => '4',
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable([
            'updated' =>
            [
                'disabled' => true,
            ],
        ]);
        $this->actAs($timestampable0);
    }

}
